model:
  image_size: # width, height
    - 300
    - 300

  textbox_layer:
    min_scale: 0.1
    max_scale: 0.9

    default:
      iou_threshold: 0.5
      min_threshold: 0.5
      vertical_offsets:
        - 0.
        - 0.5
      ratios:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
      kernel_size:
        - 1
        - 5
      padding: SAME

    layer_0:
      min_threshold: 0.45

    layer_5:
        kernel_size:
          - 1
          - 1
        padding: VALID

data:
  num_samples: 3
  source: poc/test.tfrecord

eval:
  min_score: 0.5
  top_k: 400
  keep_top_k: 200
  nms_threshold: 0.5

train:
  num_readers: 1
  batch_size: 2
  queue_min: 8192
